services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    hostname: keycloak
    command: start-dev
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    
  discovery:
    build: ./discovery-service
    hostname: discovery
    ports:
      - 8761:8761
    environment:
      - PORT=8761
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1"]
      interval: 25s
      timeout: 5s
      retries: 3
      # start_period: 40s
      
  gateway:
    build: ./gateway-service
    hostname: gateway
    ports:
      - 8080:8080
    environment:
      - ISSUER_URL=http://keycloak:8081/realms/DevRealm
      - EUREKA_URI=http://discovery:8761/eureka
      - PORT=8080
    depends_on:
      discovery:
        condition: service_healthy
  echo:
    build: ./echo-service
    hostname: echo
    environment:
      - EUREKA_URI=http://discovery:8761/eureka
    depends_on:
      discovery:
        condition: service_healthy