spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8080/realms/DevRealm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      mvc:
        routes:
          - id: resource-service
#           uri: lb://resource-service
            uri: http://localhost:8082
            predicates:
              - Path=/resource/**
            filters:
              - StripPrefix=1
            
jwt:
  auth:
    converter:
      resource-id: auth_client
      principal-attribute: principal_username
      
server:
  port: 8081
