spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URL:http://localhost:8080/realms/DevRealm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
          allowedOrigins: '*'
      mvc:
        routes:
          - id: resource-service
            uri: lb://resource-service 
            predicates:
              - Path=/resource/**
            filters:
              - StripPrefix=1
            
jwt:
  auth:
    converter:
      resource-id: auth_client
      principal-attribute: principal_username
      
server:
  port: ${PORT:8080}

eureka:
  client:
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}