import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import {cn} from "@/app/lib/utils";
import { SessionProvider } from "next-auth/react";
import { NextAuthorProviders } from "./providers/next-auth-providers";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <NextAuthorProviders>
          {children}
        </NextAuthorProviders>
      </body>
    </html>
  );
}
